-- AlterTable
ALTER TABLE "Sale" ADD COLUMN     "discount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "discountType" TEXT NOT NULL DEFAULT 'amount',
ADD COLUMN     "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 0;
